version: '3.8'

services:
  admin-panel:
    build: .
    container_name: admin-panel-app
    environment:
      - REACT_APP_API_URL=http://209.74.83.122:3000
    ports:
      - "3002:80"
    restart: unless-stopped
