version: '3.8'

services:
  client:
    build: .
    container_name: cms-client
    environment:
      - REACT_APP_API_URL=http://localhost:3000
    ports:
      - "3001:80"
    restart: unless-stopped
